#!/bin/bash
# Generated by run_perf_sweep — do not edit by hand.
# Deployment: __DEPLOYMENT_NAME__
set -e

export VLLM_USE_MODELSCOPE=True
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export HCCL_OP_EXPANSION_MODE="AIV"
export HCCL_BUFFSIZE=1024
export OMP_NUM_THREADS=1
export TASK_QUEUE_ENABLE=1
export LD_PRELOAD=/usr/lib64/libjemalloc.so.2:${LD_PRELOAD:-}
export VLLM_ASCEND_ENABLE_FUSED_MC2=1
export VLLM_ASCEND_ENABLE_FLASHCOMM1=0

# 本机回环地址直连，禁止 /v1/* 请求走 http(s)_proxy，否则就绪检测与压测客户端
# 会被代理拦截（curl 通但 python urllib / ais_bench 连不上）。
export no_proxy="127.0.0.1,localhost,::1${no_proxy:+,${no_proxy}}"
export NO_PROXY="$no_proxy"

# Dump env for diff against manual launch
env | sort > "__LOG_DIR__/vllm_env.log"
which vllm > "__LOG_DIR__/vllm_which.log" 2>&1 || true
vllm --version >> "__LOG_DIR__/vllm_which.log" 2>&1 || true

exec vllm serve __MODEL_PATH__ \
  --host 127.0.0.1 \
  --port __PORT__ \
  --data-parallel-size __DP__ \
  --tensor-parallel-size __TP__ \
  --seed 1024 \
  --quantization ascend \
  --served-model-name qwen3.6 \
  --max-num-seqs __MAX_NUM_SEQS__ \
  --max-model-len 133000 \
  --max-num-batched-tokens 16384 \
  --trust-remote-code \
  --gpu-memory-utilization 0.80 \
  --enable-prefix-caching \
  --speculative_config '{"method": "qwen3_5_mtp", "num_speculative_tokens": 3}' \
  --compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY", "cudagraph_capture_sizes": __CGCS__}' \
  --additional-config '{"enable_cpu_binding":true}' \
  --async-scheduling
